- name: Create base ubuntu bionic container
  vars:
    - base_container_name: base-bionic
    - base_container_recipe: "{{ common_container_recipe_dir }}/{{ base_container_name }}.def"
    - base_container_image: "{{ common_container_dir }}/{{ base_container_name }}.sif"
  tags: base-bionic
  block:
    - name: Copy recipe
      template:
        src: "{{ base_container_name }}.def"
        dest: "{{ base_container_recipe }}.def"
    - name: Build container
      command: "/opt/singularity/bin/singularity build {{ base_container_image }} {{ base_container_recipe }}"
      args:
        creates: "{{ base_container_image }}"
      become: yes

- name: Create ubuntu bionic compile container
  vars:
    - base_container_name: base-bionic
    - base_container_image: "{{ common_container_dir }}/{{ base_container_name }}.sif"
    - container_name: base-bionic-compile
    - container_recipe: "{{ common_container_recipe_dir }}/{{ container_name }}.def"
    - container_image: "{{ common_container_dir }}/{{ container_name }}.sif"
  tags: base-bionic-compile
  block:
    - name: "Check for existance of {{ base_container_image }} container"
      stat:
        path: "{{ base_container_image }}"
      register: base_container_exists
    - name: "Missing {{ base_container_image }}"
      fail:
        msg: "The container {{ base_container_image }} is missing."
      when: base_container_exists.stat.exists == False
    - name: Create container
      when: base_container_exists.stat.exists == True
      block:
        - name: Copy recipe
          template:
            src: "{{ container_name }}.def"
            dest: "{{ container_recipe }}.def"
        - name: Build container
          command: "/opt/singularity/bin/singularity build {{ container_image }} {{ container_recipe }}"
          args:
            creates: "{{ base_container_image }}"
          become: yes

