---
# tasks file for containers
- name: Create Ubuntu Base Containers
  vars:
    - ubuntu_versions:
        - {
            version_name: bionic,
            version_number: 18.04,
        }
  include_tasks:
    file: ubuntu.yaml
  loop: "{{ ubuntu_versions }}"
  tags: always

- name: Create RStudio Containers
  vars:
    - rstudio_versions:
        - {
            base_container_name: ubuntu-bionic-compile,
            base_container_version_name: bionic,
            r_version: 4.0.0,
            rstudio_version: 1.2.5042,  # 1.3.959,
        }
#        - {
#          base_container_name: ubuntu-bionic-compile,
#          base_container_version_name: bionic,
#          r_version: 4.0.0,
#          rstudio_version: 1.3.959,
#        }
  include_tasks:
    file: RStudio.yaml
  loop: "{{ rstudio_versions }}"
  tags: always


- name: Create PopGen Containers
  vars:
    - popgen_versions:
        - {
            base_container_name: RStudio1.2.5042-R4.0.0,
            version_number: 0.1,
            arlecore: {
              version: 3.5,
              url: http://cmpg.unibe.ch/software/arlequin35/linux/arlecore_linux.zip,
              checksum: 79d7ce0c126c32f88a66290aabd29e0b2e5b2d8c46cbcf02ef95ac7cbb91ead8,
            },
            beast: {
              version: 1.8.4,
              url: https://github.com/beast-dev/beast-mcmc/releases/download/v1.8.4/BEASTv1.8.4.tgz,
              checksum: c14e93976008463108aefa34ecc23287ab70703caccf4962e36e295207120d78,
            },
            plink2: {
              version: 2.00a2.3,
              url: https://github.com/chrchang/plink-ng/releases/download/v2.00a2.3/plink2_linux_x86_64.zip,
              checksum: 3fa20a2058df542e928b11d715cc314c01d7c5961525b55fd17a088e6caa9cc9,
            },
            bcftools: {
              version: 1.10.2,
              url: https://github.com/samtools/bcftools/releases/download/1.10.2/bcftools-1.10.2.tar.bz2,
              checksum: f57301869d0055ce3b8e26d8ad880c0c1989bf25eaec8ea5db99b60e31354e2c,
            },
            admixture: {
              version: 1.3.0,
              url: http://dalexander.github.io/admixture/binaries/admixture_linux-1.3.0.tar.gz,
              checksum: 353e8b170c81f8d95946bf18bc78afda5d6bd32645b2a68658bd6781ff35703c,
            }
        }
  include_tasks:
    file: PopGen_suite.yaml
  loop: "{{ popgen_versions }}"
  tags: always