- name: Install Apache Maven
  vars:
    version_number: "{{ item.version_number }}"
    maven_dir: "{{ common_dir }}/maven"
    maven_module_dir: "{{ common_modules }}/maven"
    url: "http://apache.is.co.za/maven/maven-3/{{ version_number }}/binaries/apache-maven-{{ version_number }}-bin.tar.gz"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ maven_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/apache-maven-{{ version_number }}"
  tags:
    - never
    - maven{{ item.version_number }}
  block:
    - name: Install Apache Maven {{ version_number }}
      block:
        - name: Download, compile and install Apache Maven {{ version_number }}
          block:
          - name: Download Apache Maven {{ version_number }}
            get_url:
              url: "{{ url }}"
              dest: "{{ common_src }}/apache-maven-{{ version_number }}.tar.tgz"
              checksum: "{{ checksum }}"
          - name: Unzip Maven {{ version_number }}
            unarchive:
              src: "{{ common_src }}/apache-maven-{{ version_number }}.tar.tgz"
              dest: "/dev/shm"
              creates: "{{ unzipdir }}"
          - name: Ensure Maven dir exists
            file:
              path: "{{ maven_dir }}"
              state: directory
              mode: u=rwx,g=rwx,o=rx
          - name: Move uncompressed Maven {{ version_number }} to {{ install_dir }}
            command: "mv {{ unzipdir }} {{ install_dir }}"
            args:
              creates: "{{ install_dir }}"
#          - name: Make OpenMPI {{ version_number }} build directory
#            file:
#              path: "{{ build_dir }}"
#              state: directory
#          - name: Run OpenMPI {{ version_number }} configure
#            command: "../configure --prefix={{ install_dir }} --enable-static --with-singularity"
#            args:
#              chdir: "{{ build_dir }}"
#              creates: "{{ build_dir }}/Makefile"
#          - name: Build OpenMPI {{ version_number }}
#            make:
#              chdir: "{{ build_dir }}"
#            environment:
#              MAKEFLAGS: "-j {{ ansible_processor_count }}"
#          - name: Install OpenMPI {{ version_number }}
#            make:
#              chdir: "{{ build_dir }}"
#              target: install
#
#    - name: Install OpenMPI {{ version_number }} module
#      block:
#      - name: Check module dir
#        file:
#          path: "{{ mpi_module_dir }}"
#          state: directory
#          mode: u=rwx,g=rwx,o=rx
#      - name: Install OpenMPI module file
#        template:
#          src: openmpi.lua
#          dest: "{{ mpi_module_dir }}/{{ version_number }}.lua"
