---
# tasks file for compiled
# - { include: openmpi.yaml }

- name: Install openjdks
  vars:
    - openjdk_versions:
        - {
          version_number: "14.0.1",
          checksum: "sha256:22ce248e0bd69f23028625bede9d1b3080935b68d011eaaf9e241f84d6b9c4cc",
          url: "https://download.java.net/java/GA/jdk14.0.1/664493ef4a6946b186ff29eb326336a2/7/GPL/openjdk-14.0.1_linux-x64_bin.tar.gz",
        }
  include_tasks:
    file: openjdk.yaml
  loop: "{{ openjdk_versions }}"
  tags:
    - always

- name: Install OpenBLAS
  vars:
    - openblas_versions:
        - {
            version_number: 0.3.9,
            checksum: "sha256:17d4677264dfbc4433e97076220adc79b050e4f8a083ea3f853a53af253bc380",
        }
  include_tasks:
    file: openblas.yaml
  loop: "{{ openblas_versions }}"
  tags:
    - always

- name: Install LAPACK
  vars:
    - lapack_versions:
        - {
            version_number: 3.9.0,
            checksum: "sha256:106087f1bb5f46afdfba7f569d0cbe23dacb9a07cd24733765a0e89dbe1ad573",
        }
  include_tasks:
    file: lapack.yaml
  loop: "{{ lapack_versions }}"
  tags:
    - always

- name: Install Apache Maven
  vars:
    - apache_maven_versions:
        - {
            version_number: 3.6.3,
            checksum: "sha512:c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0"
        }
  include_tasks:
    file: apache_maven.yaml
  loop: "{{ apache_maven_versions }}"
  tags:
    - always

- name: Install Apache Hadoop
  vars:
    - apache_hadoop_versions:
        - {
            version_number: 3.2.1,
            checksum: "sha512:d62709c3d7144fcaafc60e18d0fa03d7d477cc813e45526f3646030cd87dbf010aeccf3f4ce795b57b08d2884b3a55f91fe9d74ac144992d2dfe444a4bbf34ee"
        }
  include_tasks:
    file: apache_hadoop.yaml
  loop: "{{ apache_hadoop_versions }}"
  tags:
    - always

- name: Install Apache Spark
  vars:
    - apache_spark_versions:
        - {
            version_number: 2.4.5,
            checksum: "sha512:48B931F5A2614C8B72BA26C0B77B2DD837EE6F6BC352BF41F4D018FDB8D20FAA74FD40730B418EF7FFD5BBCE335756CFB782F6A6F571FC35F5874BFC2CE7C277"
        }
  include_tasks:
    file: apache_spark.yaml
  loop: "{{ apache_spark_versions }}"
  tags:
    - always

- name: Install openmpis
  vars:
    - openmpi_versions:
        - {
          version_number: "4.0.3",
          checksum: "sha256:1402feced8c3847b3ab8252165b90f7d1fa28c23b6b2ca4632b6e4971267fd03",
          url: "https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.3.tar.bz2",
        }
        - {
          version_number: "3.1.6",
          checksum: "sha256:50131d982ec2a516564d74d5616383178361c2f08fdd7d1202b80bdf66a0d279",
          url: "https://download.open-mpi.org/release/open-mpi/v3.1/openmpi-3.1.6.tar.bz2",
        }
  include_tasks:
    file: openmpi.yaml
  loop: "{{ openmpi_versions }}"
  tags:
    - always

- name: Install pythons
  vars:
    python_versions:
      - { version_number: "2.7.18", checksum: "sha256:b62c0e7937551d0cc02b8fd5cb0f544f9405bafc9a54d3808ed4594812edef43" }
      - { version_number: "3.7.7", checksum: "sha256:06a0a9f1bf0d8cd1e4121194d666c4e28ddae4dd54346de6c343206599f02136" }
      - { version_number: "3.8.2", checksum: "sha256:2646e7dc233362f59714c6193017bb2d6f7b38d6ab4a0cb5fbac5c36c4d845df" }
      - { version_number: "3.8.3", checksum: "sha256:dfab5ec723c218082fe3d5d7ae17ecbdebffa9a1aea4d64aa3a2ecdd2e795864" }
    pip_packages:
      - pip
      - pipenv
      - ipython
  include_tasks:
    file: python.yaml
  loop: "{{ python_versions }}"
  tags:
    - always

- name: Install PRSices
  vars:
    - prsice_versions:
        - {
          version_number: "2.3.1d",
          checksum: "sha256:ce76de7b00598a96d705765b4d7aaf240a275abb6f00918aebcab1f534bded54",
          url: "https://github.com/choishingwan/PRSice/releases/download/2.3.1/PRSice_linux.231d.zip",
        }
  include_tasks:
    file: PRSice-2.yaml
  loop: "{{ prsice_versions }}"
  tags:
    - always

- name: Install Rs
  vars:
    - R_versions:
        - {
          version_number: "4.0.0",
          checksum: "sha256:06beb0291b569978484eb0dcb5d2339665ec745737bdfb4e873e7a5a75492940",
          url: "https://cran.r-project.org/src/base/R-4/R-4.0.0.tar.gz",
        }
  include_tasks:
    file: R.yaml
  loop: "{{ R_versions }}"
  tags:
    - always

- name: Install PLINKs
  vars:
    - plink_versions:
        - {
          version_number: "2.00a2.3",
          checksum: "3fa20a2058df542e928b11d715cc314c01d7c5961525b55fd17a088e6caa9cc9",
        }
  include_tasks:
    file: plink-ng.yaml
  loop: "{{ plink_versions }}"
  tags:
    - always

- name: Install monos
  vars:
    - mono_versions:
        - {
          version_number: "6.8.0.123",
          url: "https://download.mono-project.com/sources/mono/mono-6.8.0.123.tar.xz",
          checksum: "sha256:e2e42d36e19f083fc0d82f6c02f7db80611d69767112af353df2f279744a2ac5",
        }
  include_tasks:
    file: mono.yaml
  loop: "{{ mono_versions }}"
  tags:
    - always

- name: Install canvass
  vars:
    - canvas_versions:
        - {
          version_number: "1.40.0.1613",
          url: "https://github.com/Illumina/canvas/releases/download/1.40.0.1613%2Bmaster/Canvas-1.40.0.1613.master_x64.tar.gz",
          checksum: "sha256:90ed4baf70ffe7b87e1e37d7c4988379913dccb523c507ddafc1e778b5bd8ac4",
        }
  include_tasks:
    file: canvas.yaml
  loop: "{{ canvas_versions }}"
  tags:
    - always

- name: Install bcbio
  include_tasks:
    file: bcbio.yaml
  tags:
    - always

- name: Install samtools
  vars:
    - samtools_versions:
        - {
            version_number: "1.10",
            url: "https://github.com/samtools/samtools/releases/download/1.10/samtools-1.10.tar.bz2",
            checksum: "sha256:7b9ec5f05d61ec17bd9a82927e45d8ef37f813f79eb03fe06c88377f1bd03585",
        }
  include_tasks:
    file: samtools.yaml
  loop: "{{ samtools_versions }}"
  tags:
    - always

- name: Install bcftools
  vars:
    - bcftools_versions:
        - {
            version_number: "1.10.2",
            url: "https://github.com/samtools/bcftools/releases/download/1.10.2/bcftools-1.10.2.tar.bz2",
            checksum: "sha256:f57301869d0055ce3b8e26d8ad880c0c1989bf25eaec8ea5db99b60e31354e2c",
        }
  include_tasks:
    file: bcftools.yaml
  loop: "{{ bcftools_versions }}"
  tags:
    - always

- name: Install GenomeStrip
  vars:
    - genomestrip_versions:
        - {
          version_number: "2.00.1958",
          file_name: "svtoolkit_2.00.1958.tar",
          checksum: "sha256:0b4fb202971ad67ff1326c51e241abc3660428810b79c8a2f72c2de0198697d0",
        }
  include_tasks:
    file: GenomeStrip.yaml
  loop: "{{ genomestrip_versions }}"
  tags:
    - always