---
# tasks file for compiled
# - { include: openmpi.yaml }

- name: Install pythons
  vars:
    python_versions:
      - { version_number: "2.7.18", checksum: "sha256:b62c0e7937551d0cc02b8fd5cb0f544f9405bafc9a54d3808ed4594812edef43" }
      - { version_number: "3.8.2", checksum: "sha256:2646e7dc233362f59714c6193017bb2d6f7b38d6ab4a0cb5fbac5c36c4d845df" }
      - { version_number: "3.8.3", checksum: "sha256:dfab5ec723c218082fe3d5d7ae17ecbdebffa9a1aea4d64aa3a2ecdd2e795864" }
    pip_packages:
      - pip
      - pipenv
      - ipython
  include_tasks:
    file: python.yaml
  loop: "{{ python_versions }}"
  tags:
    - always
