---
# tasks file for compiled
# - { include: openmpi.yaml }

- name: Install openjdks
  vars:
    - openjdk_versions:
        - {
          version_number: "14.0.1",
          checksum: "sha256:22ce248e0bd69f23028625bede9d1b3080935b68d011eaaf9e241f84d6b9c4cc",
          url: "https://download.java.net/java/GA/jdk14.0.1/664493ef4a6946b186ff29eb326336a2/7/GPL/openjdk-14.0.1_linux-x64_bin.tar.gz",
        }
  include_tasks:
    file: openjdk.yaml
  loop: "{{ openjdk_versions }}"
  tags:
    - always

- name: Install OpenBLAS
  vars:
    - openblas_versions:
        - {
            version_number: 0.3.9,
            checksum: "sha256:17d4677264dfbc4433e97076220adc79b050e4f8a083ea3f853a53af253bc380",
        }
  include_tasks:
    file: openblas.yaml
  loop: "{{ openblas_versions }}"
  tags:
    - always

- name: Install Apache Spark
  vars:
    - apache_spark_versions:
        - {
            version_number: 2.4.5,
            checksum: "sha512:48B931F5A2614C8B72BA26C0B77B2DD837EE6F6BC352BF41F4D018FDB8D20FAA74FD40730B418EF7FFD5BBCE335756CFB782F6A6F571FC35F5874BFC2CE7C277"
        }
  include_tasks:
    file: apache_spark.yaml

- name: Install openmpis
  vars:
    - openmpi_versions:
        - {
          version_number: "4.0.3",
          checksum: "sha256:1402feced8c3847b3ab8252165b90f7d1fa28c23b6b2ca4632b6e4971267fd03",
          url: "https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.3.tar.bz2",
        }
        - {
          version_number: "3.1.6",
          checksum: "sha256:50131d982ec2a516564d74d5616383178361c2f08fdd7d1202b80bdf66a0d279",
          url: "https://download.open-mpi.org/release/open-mpi/v3.1/openmpi-3.1.6.tar.bz2",
        }
  include_tasks:
    file: openmpi.yaml
  loop: "{{ openmpi_versions }}"
  tags:
    - always

- name: Install pythons
  vars:
    python_versions:
      - { version_number: "2.7.18", checksum: "sha256:b62c0e7937551d0cc02b8fd5cb0f544f9405bafc9a54d3808ed4594812edef43" }
      - { version_number: "3.7.7", checksum: "sha256:06a0a9f1bf0d8cd1e4121194d666c4e28ddae4dd54346de6c343206599f02136" }
      - { version_number: "3.8.2", checksum: "sha256:2646e7dc233362f59714c6193017bb2d6f7b38d6ab4a0cb5fbac5c36c4d845df" }
      - { version_number: "3.8.3", checksum: "sha256:dfab5ec723c218082fe3d5d7ae17ecbdebffa9a1aea4d64aa3a2ecdd2e795864" }
    pip_packages:
      - pip
      - pipenv
      - ipython
  include_tasks:
    file: python.yaml
  loop: "{{ python_versions }}"
  tags:
    - always

- name: Install PRSices
  vars:
    - prsice_versions:
        - {
          version_number: "2.3.1d",
          checksum: "sha256:ce76de7b00598a96d705765b4d7aaf240a275abb6f00918aebcab1f534bded54",
          url: "https://github.com/choishingwan/PRSice/releases/download/2.3.1/PRSice_linux.231d.zip",
        }
  include_tasks:
    file: PRSice-2.yaml
  loop: "{{ prsice_versions }}"
  tags:
    - always

- name: Install Rs
  vars:
    - R_versions:
        - {
          version_number: "4.0.0",
          checksum: "sha256:06beb0291b569978484eb0dcb5d2339665ec745737bdfb4e873e7a5a75492940",
          url: "https://cran.r-project.org/src/base/R-4/R-4.0.0.tar.gz",
        }
  include_tasks:
    file: R.yaml
  loop: "{{ R_versions }}"
  tags:
    - always

- name: Install PLINKs
  vars:
    - plink_versions:
        - {
          version_number: "2.00a2.3",
          checksum: "3fa20a2058df542e928b11d715cc314c01d7c5961525b55fd17a088e6caa9cc9",
        }
  include_tasks:
    file: plink-ng.yaml
  loop: "{{ plink_versions }}"
  tags:
    - always