---
# tasks file for compiled
# - { include: openmpi.yaml }

- name: Install pythons
  vars:
    python_versions:
      - { version_number: "3.8.2", checksum: "sha256:2646e7dc233362f59714c6193017bb2d6f7b38d6ab4a0cb5fbac5c36c4d845df" }
      - { version_number: "3.8.3", checksum: "sha256:dfab5ec723c218082fe3d5d7ae17ecbdebffa9a1aea4d64aa3a2ecdd2e795864" }
    pip_packages:
      - pip
      - pipenv
  include_tasks:
    file: python.yaml
  loop: "{{ python_versions }}"
  tags:
    - always
