- name: Install OpenMPI
  block:
    - name: Install OpenMPI {{ version_number }}
      block:
        - name: Download, compile and install OpenMPI {{ version_number }}
          block:
          - name: Download OpenMPI {{ version_number }}
            get_url:
              url: https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-{{ version_number }}.tar.bz2
              dest: "{{ common_src }}/openmpi-{{ version_number }}.tar.bz2"
              checksum: sha256:1402feced8c3847b3ab8252165b90f7d1fa28c23b6b2ca4632b6e4971267fd03
          - name: Unzip OpenMPI {{ version_number }}
            unarchive:
              src: "{{ common_src }}/openmpi-{{ version_number }}.tar.bz2"
              dest: "/dev/shm/"
              creates: "{{ unzipdir }}"
          - name: Make OpenMPI {{ version_number }} build directory
            file:
              path: "{{ build_dir }}"
              state: directory
          - name: Run OpenMPI {{ version_number }} configure
            command: "../configure --prefix={{ install_dir }} --enable-static --with-singularity"
            args:
              chdir: "{{ build_dir }}"
              creates: "{{ build_dir }}/Makefile"
          - name: Build OpenMPI {{ version_number }}
            make:
              chdir: "{{ build_dir }}"
          - name: Install OpenMPI {{ version_number }}
            make:
              chdir: "{{ build_dir }}"
              target: install

        - name: Install OpenMPI {{ version_number }} module
          block:
          - name: Check module dir
            file:
              path: "{{ mpi_module_dir }}"
              state: directory
              mode: u=rwx,g=rwx,o=rx
          - name: Install OpenMPI module file
            template:
              src: openmpi.lua
              dest: "{{ mpi_module_dir }}/{{ version_number }}.lua"

      vars:
        version_number: "4.0.3"
        install_dir: "{{ mpi_dir }}/{{ version_number }}"
        unzipdir: "/dev/shm/openmpi-{{ version_number }}"
        build_dir: "{{ unzipdir }}/build"
      tags:
        - openmpi4.0.3
  vars:
    mpi_dir: "{{ common_dir }}/openmpi"
    mpi_module_dir: "{{ common_modules }}/openmpi"
  tags:
    - never
    - MPI