---
# tasks file for all
- name: Initialise directory structure
  block:
    - name: Check common directories
      file:
        path: "{{ item }}"
        state: directory
        mode: u=rwx,g=rwx,o=rx,g+s
        group: "{{ admin_group }}"
      loop:
        - "{{ software_root }}"
        - "{{ modules_dir }}"
        - "{{ astro_dir }}"
        - "{{ astro_container_dir }}"
        - "{{ astro_container_recipe_dir }}"
        - "{{ astro_src }}"
        - "{{ astro_modules }}"
        - "{{ bio_dir }}"
        - "{{ bio_container_dir }}"
        - "{{ bio_container_recipe_dir }}"
        - "{{ bio_src }}"
        - "{{ bio_modules }}"
        - "{{ common_dir }}"
        - "{{ common_container_dir }}"
        - "{{ common_container_recipe_dir }}"
        - "{{ common_src }}"
        - "{{ common_modules }}"
  tags:
    - always
    - init
